language: node_js
node_js:
  - "stable"
script:
  - npm test
  - npm run build

deploy:
  provider: pages
  strategy: git
  token: $github_token     # same env var in Travis
  keep_history: true
  local_dir: build
  cleanup: false           # replaces skip_cleanup
  on:
    branch: main
